export type NewsItem = {
  id: string;
  title: string;
  source: string;
  url: string;
  publishedAt: string;
  country: "FR" | "EU" | "US";
  tags: string[];
  importanceScore: number;
  summaryBullets: string[];
};

export const mockBreakingItems: NewsItem[] = [
  {
    id: "brk-1",
    title: "La BCE augmente ses taux directeurs de 50 points de base",
    source: "Reuters",
    url: "https://example.com/bce-taux",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    country: "EU",
    tags: ["Banque Centrale", "Inflation", "Politique Monétaire"],
    importanceScore: 92,
    summaryBullets: [
      "Taux directeur principal passe de 2,5% à 3%",
      "Décision unanime du conseil des gouverneurs",
      "Christine Lagarde évoque une inflation persistante à 8,1%",
      "Prévisions de croissance revues à la baisse pour 2024",
    ],
  },
  {
    id: "brk-2",
    title: "Budget 2024 : le déficit public français atteint 5,4% du PIB",
    source: "Les Échos",
    url: "https://example.com/budget-deficit",
    publishedAt: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    country: "FR",
    tags: ["Budget", "Déficit", "Dette"],
    importanceScore: 88,
    summaryBullets: [
      "Dérapage budgétaire supérieur aux prévisions initiales",
      "Commission européenne ouvre une procédure de déficit excessif",
      "Plan d'économies de 20 milliards annoncé par Bercy",
      "Gel de certaines dépenses publiques dès le T2 2024",
    ],
  },
  {
    id: "brk-3",
    title: "Fed maintient ses taux mais signale une pause probable",
    source: "Bloomberg",
    url: "https://example.com/fed-pause",
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    country: "US",
    tags: ["Banque Centrale", "Fed", "Taux"],
    importanceScore: 85,
    summaryBullets: [
      "Taux maintenus dans la fourchette 5,25%-5,50%",
      "Jerome Powell évoque des 'progrès significatifs' sur l'inflation",
      "Dot plot suggère 2 baisses de taux en 2024",
      "Marchés anticipent un pivot au T3 2024",
    ],
  },
  {
    id: "brk-4",
    title: "Nouvelle taxe sur les superprofits bancaires adoptée",
    source: "Le Monde",
    url: "https://example.com/taxe-banques",
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    country: "FR",
    tags: ["Fiscalité", "Banques", "Taxation"],
    importanceScore: 78,
    summaryBullets: [
      "Taux de 33% sur les profits exceptionnels depuis 2022",
      "Recettes estimées à 2 milliards d'euros",
      "Fédération bancaire française dénonce une 'double taxation'",
      "Mesure applicable dès l'exercice fiscal 2024",
    ],
  },
  {
    id: "brk-5",
    title: "Chômage US : baisse surprise à 3,5%",
    source: "CNBC",
    url: "https://example.com/chomage-us",
    publishedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    country: "US",
    tags: ["Emploi", "Chômage", "Macro"],
    importanceScore: 81,
    summaryBullets: [
      "350 000 emplois créés en janvier, vs 180 000 attendus",
      "Taux de participation en hausse à 63,4%",
      "Salaires horaires +0,4% sur un mois",
      "Marché du travail reste résilient malgré les hausses de taux",
    ],
  },
  {
    id: "brk-6",
    title: "Zone Euro : l'inflation ralentit à 6,9% en janvier",
    source: "Eurostat",
    url: "https://example.com/inflation-euro",
    publishedAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    country: "EU",
    tags: ["Inflation", "Macro", "Prix"],
    importanceScore: 86,
    summaryBullets: [
      "Décélération après un pic à 10,6% en octobre 2023",
      "Inflation core reste élevée à 5,3%",
      "Énergie : -11% sur un an, alimentation +13%",
      "Objectif BCE de 2% toujours hors de portée",
    ],
  },
  {
    id: "brk-7",
    title: "Plan de relance européen : déblocage de 15 Mds€ pour la France",
    source: "AFP",
    url: "https://example.com/relance-ue",
    publishedAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    country: "EU",
    tags: ["Budget", "UE", "Relance"],
    importanceScore: 74,
    summaryBullets: [
      "Validation des réformes structurelles par Bruxelles",
      "Fonds destinés à la transition énergétique et digitale",
      "Calendrier de versement : 3 tranches d'ici fin 2024",
      "Conditionnalité renforcée sur les objectifs climat",
    ],
  },
  {
    id: "brk-8",
    title: "Dollar : plus forte hausse hebdomadaire depuis 6 mois",
    source: "Financial Times",
    url: "https://example.com/dollar-hausse",
    publishedAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    country: "US",
    tags: ["Change", "Dollar", "Macro"],
    importanceScore: 69,
    summaryBullets: [
      "EUR/USD retombe sous 1,08",
      "Anticipations de taux Fed plus élevés plus longtemps",
      "DXY Index +2,3% sur la semaine",
      "Impact sur les émergents et matières premières",
    ],
  },
  {
    id: "brk-9",
    title: "Réforme des retraites : impact budgétaire révisé à 12 Mds€",
    source: "Ministère de l'Économie",
    url: "https://example.com/retraites-budget",
    publishedAt: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    country: "FR",
    tags: ["Budget", "Retraites", "Social"],
    importanceScore: 76,
    summaryBullets: [
      "Économies attendues à horizon 2030",
      "Recul de l'âge légal à 64 ans maintenu",
      "Opposition syndicale toujours mobilisée",
      "Conseil constitutionnel valide le texte",
    ],
  },
  {
    id: "brk-10",
    title: "Commerce USA-Chine : tensions sur les semi-conducteurs",
    source: "Wall Street Journal",
    url: "https://example.com/us-china-tech",
    publishedAt: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
    country: "US",
    tags: ["Commerce", "Géopolitique", "Tech"],
    importanceScore: 82,
    summaryBullets: [
      "Nouvelles restrictions US sur l'export de puces avancées",
      "Pékin menace de représailles commerciales",
      "Impact sur les chaînes d'approvisionnement mondiales",
      "Semi-conducteurs : enjeu stratégique majeur pour 2024-2030",
    ],
  },
];

export const mockDailyBriefItems: NewsItem[] = [
  {
    id: "brief-1",
    title: "France : croissance du PIB au T4 2023 révisée à +0,2%",
    source: "INSEE",
    url: "https://example.com/pib-france",
    publishedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    country: "FR",
    tags: ["PIB", "Croissance", "Macro"],
    importanceScore: 65,
    summaryBullets: [
      "Révision à la hausse vs estimation flash à +0,1%",
      "Consommation des ménages en légère reprise",
      "Investissement des entreprises en recul de 0,3%",
      "Prévisions 2024 : croissance annuelle à +1,0%",
    ],
  },
  {
    id: "brief-2",
    title: "Zone Euro : indice PMI manufacturier à 46,5 en janvier",
    source: "S&P Global",
    url: "https://example.com/pmi-euro",
    publishedAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    country: "EU",
    tags: ["PMI", "Industrie", "Indicateur"],
    importanceScore: 58,
    summaryBullets: [
      "Contraction pour le 8ème mois consécutif (seuil à 50)",
      "Allemagne en difficulté avec un PMI à 43,2",
      "Nouvelles commandes en baisse continue",
      "Services restent en expansion à 52,4",
    ],
  },
  {
    id: "brief-3",
    title: "Inflation en France : hausse de 5,2% sur un an en janvier",
    source: "INSEE",
    url: "https://example.com/inflation-france",
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    country: "FR",
    tags: ["Inflation", "Prix", "Macro"],
    importanceScore: 72,
    summaryBullets: [
      "Ralentissement après 5,9% en décembre",
      "Alimentation : toujours la principale contribution (+12%)",
      "Énergie : déflation de -3% grâce au bouclier tarifaire",
      "Inflation core stable à 6,0%",
    ],
  },
  {
    id: "brief-4",
    title: "USA : ventes au détail en hausse de 0,8% en janvier",
    source: "Census Bureau",
    url: "https://example.com/ventes-us",
    publishedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    country: "US",
    tags: ["Consommation", "Ventes", "Macro"],
    importanceScore: 61,
    summaryBullets: [
      "Performance supérieure aux attentes (+0,3% anticipé)",
      "Automobile et e-commerce en forte progression",
      "Résilience du consommateur américain confirmée",
      "Soutien à l'économie malgré la hausse des taux",
    ],
  },
  {
    id: "brief-5",
    title: "Dette publique française : 2 950 Mds€ au T4 2023",
    source: "Banque de France",
    url: "https://example.com/dette-france",
    publishedAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    country: "FR",
    tags: ["Dette", "Budget", "Finances Publiques"],
    importanceScore: 70,
    summaryBullets: [
      "Dette publique représente 111,8% du PIB",
      "Hausse de 58 Mds€ sur le trimestre",
      "Charge de la dette en augmentation avec les taux",
      "Trajectoire de désendettement reportée après 2027",
    ],
  },
  {
    id: "brief-6",
    title: "Zone Euro : taux de chômage stable à 6,5%",
    source: "Eurostat",
    url: "https://example.com/chomage-euro",
    publishedAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    country: "EU",
    tags: ["Emploi", "Chômage", "Social"],
    importanceScore: 54,
    summaryBullets: [
      "Plus bas niveau historique maintenu",
      "Disparités entre pays : Espagne 11,5%, Allemagne 3,1%",
      "Chômage des jeunes en recul à 14,2%",
      "Marché du travail résiste malgré le ralentissement",
    ],
  },
  {
    id: "brief-7",
    title: "Trésor français : emprunt à 10 ans à 3,15%",
    source: "AFT",
    url: "https://example.com/oat-france",
    publishedAt: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
    country: "FR",
    tags: ["Taux", "Dette", "Marchés"],
    importanceScore: 48,
    summaryBullets: [
      "Adjudication de 10 Mds€ avec un taux de couverture de 2,1x",
      "Spread avec le Bund allemand à 60 points de base",
      "Hausse des rendements liée aux anticipations de taux BCE",
      "Demande internationale soutenue",
    ],
  },
  {
    id: "brief-8",
    title: "USA : indice des prix à la production en hausse de 0,3%",
    source: "Bureau of Labor Statistics",
    url: "https://example.com/ppi-usa",
    publishedAt: new Date(Date.now() - 34 * 60 * 60 * 1000).toISOString(),
    country: "US",
    tags: ["Inflation", "Prix", "Producteurs"],
    importanceScore: 52,
    summaryBullets: [
      "Accélération vs +0,1% le mois précédent",
      "Énergie : +1,2% après deux mois de baisse",
      "Services en hausse de 0,4%",
      "Signaux de pressions inflationnistes persistantes",
    ],
  },
];

export const mockSources = [
  { id: "1", name: "Reuters", country: "EU", category: "Généraliste", enabled: true },
  { id: "2", name: "Bloomberg", country: "US", category: "Finance", enabled: true },
  { id: "3", name: "Les Échos", country: "FR", category: "Économie", enabled: true },
  { id: "4", name: "Financial Times", country: "EU", category: "Finance", enabled: true },
  { id: "5", name: "Le Monde", country: "FR", category: "Généraliste", enabled: true },
  { id: "6", name: "Wall Street Journal", country: "US", category: "Finance", enabled: false },
  { id: "7", name: "Eurostat", country: "EU", category: "Statistiques", enabled: true },
  { id: "8", name: "INSEE", country: "FR", category: "Statistiques", enabled: true },
  { id: "9", name: "CNBC", country: "US", category: "Finance", enabled: false },
  { id: "10", name: "AFP", country: "FR", category: "Généraliste", enabled: true },
];
